title: full stack with benefits
author: Manuel Spagnolo
github:  shikaan
twitter:  spagmanuel
email: spagnolo.manu@gmail.com

permalink: /:slug.html

favicon: "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>ğŸ“</text></svg>"

remote_theme: riggraz/no-style-please

theme_config:
  back_home_text: "< Home"
  date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed
  - jekyll-seo-tag